### ISSUE TITLE
neon_simd.cpp missing in sources

### ISSUE THREAD

**Issue by jerin-thirdai** [abdes/cryptopp-cmake#22]
Using this to build a package on Apple M1. Errored saying [`CPU_ProbeNEON`](https://github.com/weidai11/cryptopp/search?q=CPU_ProbeNEON) not found. Is there a reason why this file is not included?

The following fixes builds locally for me:

```diff
diff --git a/cryptopp/sources.cmake b/cryptopp/sources.cmake
index ed49b2d..c14cad4 100644
--- a/cryptopp/sources.cmake
+++ b/cryptopp/sources.cmake
@@ -108,6 +108,7 @@ set(cryptopp_SOURCES
     mqueue.cpp
     mqv.cpp
     nbtheory.cpp
+    neon_simd.cpp
     oaep.cpp
     osrng.cpp
     padlkrng.cpp
```

**Comment by botanegg** [comment]
I catch this, and fixes works for me  
Also works for next arch/platforms:  
	android  (using NDK 25.1.8937393)
	ios  (xcode 13.4.1 with ios11 target)
	linux-archlinux-x86_64  
	linux-rpi-arm-buster  
	linux-ubuntu-focal-x86_64  
	linux-ubuntu-jammy-x86_64  
	linux-ubuntu-jammy-x86_64  
	win-nt-x86  
	win-nt-x86_64

**Comment by abdes** [comment]
Thanks for reporting this, and for suggesting the fix.

So, We use the special target `sources` in the crypto++ project to generate the list of sources files to use in the cmake project. That command currenlty does not include that source file in the generated lists.

While I will add it because it fixes the problem when building on Apple M1/M2, I still would like to get a confirmation from @noloader for why it is not included in the `make sources` output.


```
