### ISSUE TITLE
Add mingw tests

### ISSUE THREAD

**Issue by Vollstrecker** [abdes/cryptopp-cmake#69]

**Comment by noloader** [comment]
`CRYPTOPP_BOOL_X32` is x32, which is ILP32 data model on x86_64. See, for example, https://wiki.debian.org/X32Port and https://en.wikipedia.org/wiki/X32_ABI.

For Windows, you want either `CRYPTOPP_BOOL_X86` (32-bit) or `CRYPTOPP_BOOL_X64` (64-bit).

In fact, I seem to recall we mostly backed out x32 support a couple of years ago for the inline assembly stuff. Someone raised a question that it may be incorrect, so we just nuked it. Just about no one should miss it since it is such a rare platform.

**Comment by noloader** [comment]
> Setting DISABLE_ASM which leads to a segfault in cryptest.

This should definitely not happen. I'll see if I can reproduce it.

**Comment by Vollstrecker** [comment]
For reproduction: CMAKE_BUILD_TYPE=Release -DDISABLE_ASM=ON does the same (assumed it, but now confirmed).

For the BOOL:
__ILP32__ and _ILP32 are defined
__x86_64__ is not, so no BOOL_X32
_M_X64 is not defined, so also no BOOL_X64
_X86_ and i386 are defined, so BOOL_X86 should be useable

When compiling without any -O the assembler complains about bp is being used in gcm.cpp around line 822 (and sha.cpp, but t looks similar). bp is mentioned at line 721 and only not used when BOOL_X32 is set, but when it is set the assembler complains that pushq instead of push is used in cpu.cpp around line 432 (from my mind). It is used on line 524 and can only be avoided when X32 and X64 are not set. I guess there is somewhere a conflict.

**Comment by Vollstrecker** [comment]
Forgot to mention: atm. DISABLE_ASM is hardcoded in cryptopp/CMakeLists.txt line 234. You maybe need to comment (or change to something other you want to check) to see all the mentioned problems.
