### ISSUE TITLE
Cannot include with 'cryptopp/' prefix in Android build with NDK bundled CMake 3.22.1

### ISSUE THREAD

**Issue by Steveice10** [abdes/cryptopp-cmake#89]
When included in an Android project build using the NDK's bundled CMake 3.22.1, any includes prefixed with the 'cryptopp/' path do not work. It seems that [this line](https://github.com/abdes/cryptopp-cmake/blob/master/cryptopp/CMakeLists.txt#L1186) does not end up getting the parent path correctly for the include directories.

I've been able to get it to work thus far with this workaround in my CMake logic:

```
if(ANDROID)
    get_target_property(CRYPTOPP_INCLUDES cryptopp INTERFACE_INCLUDE_DIRECTORIES)
    foreach(CRYPTOPP_INCLUDE ${CRYPTOPP_INCLUDES})
        if("${CRYPTOPP_INCLUDE}" MATCHES "\\$<BUILD_INTERFACE:(.*)/cryptopp>")
            target_include_directories(cryptopp PUBLIC $<BUILD_INTERFACE:${CMAKE_MATCH_1}>)
            break()
        endif()
    endforeach()
endif()
```

**Comment by abdes** [comment]
Is this a new behaviour for 8.8.0 release or was it the same for 8.7.0?

**Comment by Steveice10** [comment]
Happens on both versions from my testing. We're on 8.7.0 but I tried upgrading to 8.8.0 to check if it fixed it.

**Comment by Steveice10** [comment]
This seems to be a cmake_path bug others have experienced with specific builds of CMake: https://github.com/scikit-build/cmake-python-distributions/issues/221

For us it’s the Android NDK bundled CMake.

We do use get_filename_component(… DIRECTORY) successfully in our own CMake logic, would that be a suitable alternative to cmake_path?

**Comment by abdes** [comment]
Yes. We will probably do that too... expect a fix soon

**Comment by abdes** [comment]
Looking back into this, the cmake documentation clearly states that cmake_path should be used instead of 

> Changed in version 3.20: This command has been superseded by the [cmake_path()](https://cmake.org/cmake/help/latest/command/cmake_path.html#command:cmake_path) command, except for REALPATH, which is now offered by [file(REAL_PATH)](https://cmake.org/cmake/help/latest/command/file.html#real-path), and PROGRAM, now available in [separate_arguments(PROGRAM)](https://cmake.org/cmake/help/latest/command/separate_arguments.html#command:separate_arguments).

https://cmake.org/cmake/help/latest/command/get_filename_component.html

Therefore, the most appropriate resolution for this issue would be to fix the bug in the broken build in https://github.com/scikit-build/cmake-python-distributions/issues/221 instead of hacking around it.

**Comment by abdes** [comment]
I understand your problem. I looked around, and there seems to be an easy fix for you at https://developer.android.com/studio/projects/install-ndk#vanilla_cmake.

The CMake version included with the NDK is archaic for this project. As clearly stated in the project bylaws, this is a modern CMake version that will not accommodate archaic versions.

Here is my proposal to you:

1. Follow the steps above to update to a modern working version of CMake in your NDK environment.
2. If that creates too many issues of backward compatibility for you, but please only then, propose a PR for this project where you would guard protect the use of [get_filename_component](https://cmake.org/cmake/help/latest/command/get_filename_component.html) ONLY when it is an NDK build.

How does this sound?

**Comment by Steveice10** [comment]
> The CMake version included with the NDK is archaic for this project. As clearly stated in the project bylaws, this is a modern CMake version that will not accommodate archaic versions.

I wouldn’t consider 3.22.1, a version from under 2 years ago, as archaic? We are already using the steps you linked to specify a CMake version, and 3.22.1 is the latest version available to use from the NDK.

**Comment by abdes** [comment]
My understanding is that you can use any version you want, that you just need to install it from outside of the NDK.And I said archaic because the NDK doc on the web was mentioning 3.17.I’m not an expert in the NDK.Please install and use a version of CMake that does not have the cmske_path bug.On 2 Oct 2023, at 3:25 PM, Steveice10 ***@***.***> wrote:﻿

The CMake version included with the NDK is archaic for this project. As clearly stated in the project bylaws, this is a modern CMake version that will not accommodate archaic versions.

I wouldn’t consider 3.22.1, a version from under 2 years ago, as archaic? We are already using the steps you linked to specify a CMake version, and 3.22.1 is the latest version available to use from the NDK.

**Comment by Steveice10** [comment]
You should probably specify that your minimum version is higher than 3.22.1 then, since it is apparently only conditionally supported by this project.

**Comment by abdes** [comment]
> You should probably specify that your minimum version is higher than 3.22.1 then, since it is apparently only conditionally supported by this project.

Thank you for the PR #102. It was minimal and clean. Already merged.

This type of workaround does not conflict with the project philosophy of pushing towards using the widely used recent versions of CMake. Like every software, CMake does have bugs, and I'm OK that we work around them.
